# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rev_memcache}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Rudenko"]
  s.date = %q{2010-02-19}
  s.description = %q{Rev memcache client}
  s.email = %q{ceo@prepor.ru}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/test.rb",
     "lib/rev_memcache.rb",
     "lib/rev_memcache/deferrable.rb",
     "lib/t.rb",
     "rev_memcache.gemspec"
  ]
  s.homepage = %q{http://github.com/prepor/rev_memcache}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rev memcache client}
  s.test_files = [
    "examples/test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rev>, [">= 0"])
    else
      s.add_dependency(%q<rev>, [">= 0"])
    end
  else
    s.add_dependency(%q<rev>, [">= 0"])
  end
end

